#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -z ${AUTO_UPDATE+x} ]] || [[ "${AUTO_UPDATE}" == "true" ]]; then
    dockforgeown -R abc:abc \
        /app/Jackett
fi

# permissions
dockforgeown -R abc:abc \
    /config
